# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Specifies models available in GovCloud. All other settings are currently
# inherited from system defaults.


notes: Default settings for Pattern1 (BDA) GovCloud
classes: []

summarization:
     model: anthropic.claude-3-7-sonnet-20250219-v1:0
discovery:
  with_ground_truth:
    model_id: amazon.nova-pro-v1:0
  without_ground_truth:
    model_id: amazon.nova-pro-v1:0
agents:
  error_analyzer:
    model_id: anthropic.claude-3-7-sonnet-20250219-v1:0      
  chat_companion:
    model_id: anthropic.claude-3-7-sonnet-20250219-v1:0
