# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# All settings are currently inherited from system defaults.

notes: Default settings for Pattern1 (BDA)
classes: []